- pkg/meroxa/function.go
Used in https://github.com/meroxa/cli/pull/328.
Part of https://github.com/meroxa/turbine-project/issues/187
> feat: Include logs as part of functions

- .gitignore
- pkg/meroxa/application.go
- pkg/meroxa/application_test.go
https://github.com/meroxa/meroxa-go/issues/117
> App Resource includes a collection field

- pkg/meroxa/application.go
- pkg/meroxa/build.go
- pkg/meroxa/connector.go
- pkg/meroxa/endpoint.go
- pkg/meroxa/environment.go
- pkg/meroxa/function.go
- pkg/meroxa/log.go
- pkg/meroxa/meroxa.go
- pkg/meroxa/meroxa_test.go
- pkg/meroxa/pipeline.go
- pkg/meroxa/resource.go
- pkg/meroxa/resource_types.go
- pkg/meroxa/source.go
- pkg/meroxa/transform.go
- pkg/meroxa/user.go
- pkg/mock/mock_client.go
In preparation for the `Meroxa-Account-Id` header.
> Adding headers on `MakeRequest` interface

- .github/workflows/dependabot-auto-merge-go.yml
Automerge Dependabot PRs that pass automated tests.
Related to https://github.com/meroxa/engineering/issues/24
> Add workflow to automatically close dependabot PRs

- pkg/meroxa/account.go
- pkg/meroxa/account_test.go
- pkg/meroxa/application.go
- pkg/meroxa/build.go
- pkg/meroxa/connector.go
- pkg/meroxa/connector_test.go
- pkg/meroxa/deployment.go
- pkg/meroxa/endpoint.go
- pkg/meroxa/environment.go
- pkg/meroxa/function.go
- pkg/meroxa/log.go
- pkg/meroxa/meroxa.go
- pkg/meroxa/pipeline.go
- pkg/meroxa/resource.go
- pkg/meroxa/resource_types.go
- pkg/meroxa/source.go
- pkg/meroxa/transform.go
- pkg/meroxa/user.go
Add `Meroxa-Account-UUID` as part of the client headers, and update APIs implementation to send the client headers as part of the request.
> Client Headers

- pkg/meroxa/deployment.go
- pkg/meroxa/deployment_test.go
Deployment spec should be json, not string
> Ensure deployment spec is json

- pkg/meroxa/meroxa.go
Fixes: https://github.com/meroxa/cli/issues/476
> Pull existing headers from options first

- pkg/meroxa/application.go
- pkg/meroxa/function.go
Most of the changes were redundant... leaving the remaining changes in this PR to make setting function status clearer.
> Make Function state valid values explicit

- pkg/meroxa/application.go
- pkg/meroxa/application_test.go
Include status and type so that multiple calls are not necessary in the CLI
Fixes https://github.com/meroxa/turbine-project/issues/129
> Include type and status in the Application description

- pkg/meroxa/application.go
- pkg/meroxa/application_test.go
- pkg/meroxa/meroxa.go
- pkg/mock/mock_client.go
Fixes https://github.com/meroxa/turbine-project/issues/280
> Application logs as one view/endpoint

- pkg/meroxa/account_test.go
- pkg/meroxa/meroxa.go
- pkg/meroxa/options.go
- pkg/mock/mock_client.go
Make this easy and clear for the CLI
Fixes https://github.com/meroxa/platform-api/issues/1525
> Convenient function for setting the referer header

- pkg/meroxa/function.go
Fixes https://github.com/meroxa/product/issues/632
> Expose created_at and updated_at timestamps for Functions

- pkg/meroxa/application.go
- pkg/meroxa/application_test.go
- pkg/meroxa/environment_test.go
- pkg/meroxa/meroxa.go
Fixes https://github.com/meroxa/meroxa-go/issues/153.
Part of the addition of Environments to Turbine applications.
This will be fully tested in the CLI (currently in progress)
> feat: Add environment to application

- pkg/meroxa/meroxa.go
- pkg/meroxa/resource.go
- pkg/meroxa/resource_types.go
- pkg/mock/mock_client.go
Reverts meroxa/meroxa-go#156
This should hopefully unblock the failing acceptance test suite [here](https://github.com/meroxa/cli/actions/runs/4019570506/jobs/6954570800#step:3:506)
For more context, see also https://meroxa.slack.com/archives/C03FL181C3A/p1675082577397069
> Revert "Update ResourceType list format"

- pkg/meroxa/meroxa.go
- pkg/meroxa/resource.go
- pkg/meroxa/resource_types.go
- pkg/meroxa/resource_types_test.go
- pkg/mock/mock_client.go
Related to https://github.com/meroxa/cli/issues/596
keep v1/resource-types and add v2/resource-types
> Versioned resource types

- .gitignore
- Makefile
- pkg/meroxa/application.go
- pkg/meroxa/application_test.go
- pkg/meroxa/environment_test.go
Changing type of Environment field for Application to use EntityIdentifier
> Use EntityIdentifier on Environment Field for Application

- pkg/meroxa/application.go
- pkg/meroxa/application_test.go
- pkg/meroxa/deployment.go
- pkg/meroxa/deployment_test.go
- pkg/meroxa/meroxa.go
- pkg/meroxa/resource_types.go
- pkg/meroxa/resource_types_test.go
- pkg/meroxa/source.go
- pkg/meroxa/source_test.go
- pkg/mock/mock_client.go
Fixes https://github.com/meroxa/meroxa-go/issues/162
It also refactors some some variable and method names that uses the V2 path to make them all consistent.
> feat(source): Add source v2

- pkg/meroxa/source.go
- pkg/meroxa/source_test.go
Adding environment to source obj as part of https://github.com/meroxa/platform-api/issues/1699
> Add environment to source obj

- pkg/meroxa/environment.go
Add ecr preflight checks required for https://github.com/meroxa/merman/pull/526 
Related to: https://github.com/meroxa/merman/pull/552 https://github.com/meroxa/platform-api/pull/1774
| before | after |
|--------|-------|
|<img width="965" alt="Screenshot 2023-03-15 at 7 03 35 PM" src="https://user-images.githubusercontent.com/31331000/225462396-32edc0c7-d77d-4254-a4c1-93c4fb6e6e5c.png">|<img width="961" alt="Screenshot 2023-03-15 at 4 08 12 PM" src="https://user-images.githubusercontent.com/31331000/225431729-bec57366-0573-4227-9d0f-7e1270087c6f.png">|
> Add ecr preflight checks

- pkg/meroxa/flink_job.go
- pkg/meroxa/flink_job_test.go
- pkg/meroxa/meroxa.go
- pkg/meroxa/source.go
- pkg/mock/mock_client.go
Supports the CLI work to describe, list, and deploy Flink Jobs
Fixes https://github.com/meroxa/product/issues/778
**Before:**
**After:**
> Flink job endpoints

- pkg/meroxa/flink_job.go
Fixes <GitHub Issue>
**Before:**
**After:**
> Flink state corrections

- pkg/meroxa/flink_job.go
Related to https://github.com/meroxa/cli/issues/761
**Before:**
**After:**
> Remove enum association from Flink Job state field

- pkg/meroxa/flink_job.go
Allow spec and spec version to be sent with the request to create a flink job
Fixes https://github.com/meroxa/product/issues/861
**Before:**
**After:**
> Add spec and version to creating a flink job

- pkg/meroxa/flink_job.go
Fixes <GitHub Issue>
**Before:**
**After:**
> Spec cannot be a string to marshal correctly

- pkg/meroxa/flink_job.go
- pkg/meroxa/flink_job_test.go
- pkg/meroxa/meroxa.go
- pkg/mock/mock_client.go
Depends on https://github.com/meroxa/platform-api/pull/2012
Part of https://github.com/meroxa/cli/issues/794
> feat: add GET /v2/flink-job/uuid/logs
